# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Gourmet' do
pod 'Firebase', '>= 2.5.0'
end

target 'GourmetTests' do
pod 'Firebase', '>= 2.5.0'
end

target 'GourmetUITests' do
pod 'Firebase', '>= 2.5.0'
end

