# Uncomment this line to define a global platform for your project
platform :ios, ‘9.2’
# Uncomment this line if you're using Swift
use_frameworks!

target 'gourmet' do
pod 'Firebase', '>= 2.5.0'
pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage', '~> 2.0'
end

target 'gourmetTests' do
end

target 'gourmetUITests' do
end

